import React from 'react'
import QuickAccessPanel from '../../layout/homelayout/QuickAccessPanel'
import XeberSwiper from '../../layout/homelayout/XeberSwiper'
import MekanSlider from '../../layout/commonlayout/MekanSlider'
import FotoXronikaSlider from '../../layout/commonlayout/FotoXronikaSlider'
import MekanSliderWithNav from '../../components/common components/MekanSliderWithNav'
import Main_header from '../../components/header_copm'
import Resmi_xronika from '../../components/resmi_xronika'

function Home() {
  return (
    <>
      <Main_header></Main_header>
      <XeberSwiper />
      <Resmi_xronika></Resmi_xronika>
      <QuickAccessPanel />
      <FotoXronikaSlider />
      <MekanSlider />
      {/* <MekanSliderWithNav /> */}
      <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac dignissim velit. Nulla laoreet semper euismod. Fusce at ligula eu erat facilisis mollis. Cras commodo condimentum neque, eget posuere tortor feugiat et. Fusce et vestibulum justo, quis malesuada massa. Cras viverra feugiat erat ac sagittis. Nulla scelerisque metus congue ligula mattis, eu feugiat nibh placerat. Curabitur at suscipit velit. Vivamus nunc nunc, sagittis nec velit ac, molestie tincidunt tellus. Mauris varius ut quam id malesuada.

        Nunc egestas a ante id mattis. Integer tempor ornare nisl, vel suscipit dui mattis vel. Donec mollis neque at tincidunt aliquam. Curabitur et orci a mi porttitor tempus. Nulla pretium ligula et laoreet tempor. In faucibus ac velit ac cursus. Aenean porta feugiat augue. Etiam auctor mattis metus sed viverra. Nam et pharetra elit, in vulputate mauris. Sed facilisis eros non orci fringilla, sed elementum erat imperdiet. Duis vitae porttitor enim. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;

        Donec lacus erat, feugiat sed erat nec, convallis bibendum massa. Nulla vitae iaculis tellus. Cras quis molestie sem. Sed vitae feugiat mi, sed blandit felis. Praesent tristique nisi eu faucibus fringilla. Aenean ut dignissim lectus. Suspendisse vel velit et eros fringilla convallis aliquam at orci. Etiam vitae dolor quis mauris mollis faucibus accumsan vel velit. Pellentesque convallis lacus vel tellus pharetra, eu convallis justo tincidunt. Cras commodo mollis sem non facilisis. Phasellus at iaculis quam, eget efficitur sem. Pellentesque vulputate quis felis ut pharetra. Mauris augue sapien, interdum at egestas sed, convallis sed nisl. Morbi sit amet lectus ac tellus dapibus sagittis.

        Nulla facilisi. Integer faucibus ornare lorem nec hendrerit. Cras a lacus est. Aliquam interdum faucibus dolor, sit amet aliquet leo faucibus vel. Maecenas semper, lectus vel porttitor venenatis, dolor urna laoreet nibh, quis pharetra libero eros ut ligula. Duis viverra mi non orci congue sollicitudin. Vivamus facilisis ultrices placerat. Mauris eleifend enim sit amet ligula pulvinar lobortis. Integer dapibus et eros ac pellentesque. Suspendisse nec aliquam arcu. Maecenas suscipit, turpis eget blandit bibendum, nisi lacus hendrerit odio, eget fringilla massa mi quis mauris. Vivamus auctor elit sed erat tempor dictum.

        Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam quam metus, ornare a ligula et, lobortis fermentum sem. Quisque malesuada vitae purus ac hendrerit. Proin maximus commodo dignissim. Sed eget pretium odio, sit amet lacinia dui. Sed semper odio sit amet pellentesque sollicitudin. Nam vel ultricies leo. Sed molestie tellus ut metus faucibus, ut sagittis justo faucibus. Pellentesque molestie, orci quis laoreet finibus, quam sapien rutrum libero, in blandit massa ex et turpis. Sed tincidunt, sapien nec fermentum molestie, urna leo rutrum felis, sed efficitur dui nulla quis magna.
      </div>
    </>
  )
}

export default Home